In [1]:
from PIL import Image
from os import listdir
from os.path import isdir
from numpy import asarray, expand_dims
import numpy as np
import os


In [2]:
!unzip faces.zip


Archive:  faces.zip
   creating: faces/
   creating: faces/train/
   creating: faces/train/deiski/
  inflating: faces/train/deiski/AGGT2684.JPG  
  inflating: faces/train/deiski/AGGT2684_flip.JPG  
  inflating: faces/train/deiski/AGIJ8108.JPG  
  inflating: faces/train/deiski/AGIJ8108_flip.JPG  
  inflating: faces/train/deiski/AHAD5612.JPG  
  inflating: faces/train/deiski/AHAD5612_flip.JPG  
  inflating: faces/train/deiski/ANFX1598.JPG  
  inflating: faces/train/deiski/ANFX1598_flip.JPG  
  inflating: faces/train/deiski/ANJC2104.JPG  
  inflating: faces/train/deiski/ANJC2104_flip.JPG  
  inflating: faces/train/deiski/ASKJ7426.JPG  
  inflating: faces/train/deiski/ASKJ7426_flip.JPG  
  inflating: faces/train/deiski/AVSY9849.JPG  
  inflating: faces/train/deiski/AVSY9849_flip.JPG  
  inflating: faces/train/deiski/BGRD9737.JPG  
  inflating: faces/train/deiski/BGRD9737_flip.JPG  
  inflating: faces/train/deiski/BHYM9667.JPG  
  inflating: faces/train/deiski/BHYM9667_flip.JPG  
  inflatin

Passa o path do arquivo, abre o arquivo como imagem, converte em RGB e em numpy, e retorna.

In [3]:
def load_face(filename):
  
  # carregando imagem do arquivo
  image = Image.open(filename)
  
  #converter para RGB
  #image = Image.convert("RGB")

  return asarray(image)


In [4]:
# Carregando as faces de um diretório
def load_faces(directory_src):
  
  faces = list()

  #iterando arquivos "directory_src = nome da pasta com o nome da pessoa"
  for filename in listdir(directory_src): 
    
    path = directory_src + filename 
    
    #a leitura da imagem pode dar erro então usa try except
    try:
      faces.append(load_face(path))
    except:
      print("Erro na imagem {}".format(path))

  return faces


In [5]:
## carregando todo o dataset de imagens de faces

def load_fotos(directory_src):
  
  X, y = list(), list()

  #iterar as pastas por classes "directory_src = é a pasta faces"
  for subdir in listdir(directory_src):
    #path
    path = directory_src + subdir + '/'

    if not isdir(path):
      continue
    
    faces = load_faces(path)

    labels = [subdir for _ in range(len(faces))]

    # sumarizar progresso
    print('>Carregadas %d faces da classe: %s' % (len(faces), subdir))

    X.extend(faces)
    y.extend(labels)

  
  return asarray(X), asarray(y)

In [23]:
import matplotlib.pyplot as plt

trainX, trainy = load_fotos(directory_src="/content/faces/train/") #para gerar embeddings das faces de treinamento

## após terminar de gerar o .csv (embedding) das faces de treinamento, gerar embeddings para faces de validação também
#trainX, trainy = load_fotos(directory_src="/content/faces/validation/") #para gerar embeddings das faces de validação

print(trainX[0])

>Carregadas 14 faces da classe: deiski
>Carregadas 57 faces da classe: nikoru
[[[104 105  99]
  [109 110 104]
  [ 48  48  46]
  ...
  [180 146 118]
  [255 243 208]
  [250 255 215]]

 [[ 91  92  84]
  [ 96  97  91]
  [ 78  79  74]
  ...
  [227 196 167]
  [255 252 217]
  [251 255 219]]

 [[ 86  86  78]
  [ 47  47  39]
  [ 67  68  62]
  ...
  [255 230 199]
  [255 254 220]
  [251 255 223]]

 ...

 [[  7   7   7]
  [  7   7   7]
  [  6   8   7]
  ...
  [  8   8   8]
  [  7   7   7]
  [  8   8   8]]

 [[  7   9   8]
  [  6   8   7]
  [  5   7   6]
  ...
  [  7   7   7]
  [  6   6   6]
  [  6   6   6]]

 [[  5   6   8]
  [  5   7   6]
  [  7   9   8]
  ...
  [  7   7   5]
  [  6   6   4]
  [  8   8   8]]]


In [24]:
trainX.shape

(71, 160, 160, 3)

In [25]:
trainy.shape

(71,)

In [10]:
import tensorflow as tf
from tensorflow import keras
from keras.models import load_model
print(tf.__version__) 

model = load_model('facenet_keras.h5')


2.6.0


In [11]:
model.summary()

Model: "inception_resnet_v1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 160, 160, 3) 0                                            
__________________________________________________________________________________________________
Conv2d_1a_3x3 (Conv2D)          (None, 79, 79, 32)   864         input_1[0][0]                    
__________________________________________________________________________________________________
Conv2d_1a_3x3_BatchNorm (BatchN (None, 79, 79, 32)   96          Conv2d_1a_3x3[0][0]              
__________________________________________________________________________________________________
Conv2d_1a_3x3_Activation (Activ (None, 79, 79, 32)   0           Conv2d_1a_3x3_BatchNorm[0][0]    
________________________________________________________________________________

## **FUNÇÃO GERADORA DE EMBEDDINGS**




In [12]:
def get_embedding(model, face_pixels):
  
    # PADRONIZAÇÃO
    mean, std = face_pixels.mean(), face_pixels.std()
    face_pixels = (face_pixels - mean) / std

    # TRANSFORMAR A FACE EM 1 UNICO EXEMPLO
    # (320, 320) -> (1, 320, 320)
    samples = expand_dims(face_pixels, axis=0)
    
    
    # REALIZAR A PREDIÇÃO GERANDO O EMBEDDING
    yhat = model.predict(samples)   ##[[1,2..128]... [1,2..128] ]
    
    return yhat[0]

In [26]:
newTrainX = list()

In [27]:
#Debug para verificar se não está misturado imagens que não são (160, 160) de resolução
for face in trainX:
      print(face.shape)
      if face.shape != (160, 160, 3):
          plt.imshow(face)
          plt.title('Imagem convertida para o RGB')
          plt.show()

(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)
(160, 160, 3)


In [28]:
for face in trainX:
    embedding = get_embedding(model, face)
    newTrainX.append(embedding) # Terá uma lista de embeddings

In [29]:
newTrainX = asarray(newTrainX)
print(newTrainX.shape)

(71, 128)


In [30]:
import pandas as pd

df = pd.DataFrame(data=newTrainX)

In [31]:
df

0         1         2    ...       125       126       127
0  -0.206436 -0.746464  0.278254  ... -0.140103  0.569573  0.195775
1  -0.130806 -0.575447  0.159703  ... -0.335846  0.319535  0.132350
2   0.080751 -0.162013 -0.268597  ... -0.160151 -1.028355  0.061811
3  -0.230243 -0.999213  0.284826  ... -0.711378  0.419533  0.379627
4   0.294907 -0.873148 -0.071881  ... -0.479333 -0.307760 -0.334187
..       ...       ...       ...  ...       ...       ...       ...
66  0.202386 -0.188427  0.173479  ... -0.012687  0.109614 -0.116463
67  0.159098 -0.276151 -0.010758  ... -0.237850  0.275254 -0.033274
68  0.185437 -0.159692 -0.252401  ... -0.285102  0.000726 -0.106567
69 -0.276561 -0.756340  0.463940  ... -0.049072  0.211034  0.030878
70 -0.342623 -0.432148  0.088476  ... -0.214729 -0.652869 -0.297094

[71 rows x 128 columns]

In [32]:
df['target'] = trainy

In [33]:
df

0         1         2  ...       126       127  target
0  -0.206436 -0.746464  0.278254  ...  0.569573  0.195775  deiski
1  -0.130806 -0.575447  0.159703  ...  0.319535  0.132350  deiski
2   0.080751 -0.162013 -0.268597  ... -1.028355  0.061811  deiski
3  -0.230243 -0.999213  0.284826  ...  0.419533  0.379627  deiski
4   0.294907 -0.873148 -0.071881  ... -0.307760 -0.334187  deiski
..       ...       ...       ...  ...       ...       ...     ...
66  0.202386 -0.188427  0.173479  ...  0.109614 -0.116463  nikoru
67  0.159098 -0.276151 -0.010758  ...  0.275254 -0.033274  nikoru
68  0.185437 -0.159692 -0.252401  ...  0.000726 -0.106567  nikoru
69 -0.276561 -0.756340  0.463940  ...  0.211034  0.030878  nikoru
70 -0.342623 -0.432148  0.088476  ... -0.652869 -0.297094  nikoru

[71 rows x 129 columns]

In [34]:
df.to_csv('faces.csv', index=False)